### PR TITLE
v0.15.2 (#26)

### PR DESCRIPTION
**Pull request by cb4ds**
cran submission

### CODE REVIEW

**Comment by neuhausi** [comment]
Connie,
The merge has conflicts that must be resolved.
Isaac

**Comment by cb4ds** [comment]
Looking into it

**Comment by cb4ds** [comment]
PR appears to be corrupted - there are no file conflicts.  In fact, 4 of the 5 files were merged already into master.  Will close the pull request and issue another one.

**Comment by neuhausi** [comment]
I tried to merge and then it corrupted? Did Git corrupt it?
I

**Comment by cb4ds** [comment]
Don't know - couldn't find any signs of corruption - clean-checked out both yours and mine, rebased it, etc.  Repository looks OK from both sides.  Chalk it up to a glitch.  I sent you a separate email also.

**Pull request closed without merging**
